### ISSUE TITLE
userMedia.loopback?

### ISSUE THREAD

**Issue by psawaya** [daily-demos/spatialization#9]
Hey @lizadaily -- thank you so much for this amazingly full-featured example project and series of articles. One of the best onboardings to an API I've ever seen. :)

I'm curious about `userMedia.loopback`. In [an earlier commit](https://github.com/daily-demos/spatialization/commit/c58175aa1583908f7b54554f3d10ac38e6ad73ea) you're initializing it on Chrome-only (presumably because of the linked bug in Chromium), but it looks like you're no longer using it at all. Is it still necessary?

**Comment by lizadaily** [comment]
@psawaya Thank you for the feedback, I'm really happy to hear you've found the demo and series useful. Regarding the loopback, we are still using it [here](https://github.com/daily-demos/spatialization/blob/92b47fb9d19d5e062ee71a8ed4800a812a1136c1/src/models/userMedia.ts#L101). It just moved into a separate class (`NodeChain`) dedicated to managing the audio graph.

**Comment by psawaya** [comment]
Ah, I see. Apologies for the misunderstanding!
